import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'


var data = JSON.stringify({});

var config = {
  method: 'post',
  url: 'https://cors-anywhere.herokuapp.com/https://55e2302f-f46f-4f81-b3ce-a570d62163ad.webhook.fc.azure-automation.net/webhooks?token=%2fk%2bYP0Vuf1Q5%2ftx3L4N8tcIe7Te7FEif4RV%2bQ8a9dpE%3d',
  headers: { 
    'Content-Type': 'application/json'
  },
  data : data
};

var configStop = {
  method: 'post',
  url: 'https://cors-anywhere.herokuapp.com/https://55e2302f-f46f-4f81-b3ce-a570d62163ad.webhook.fc.azure-automation.net/webhooks?token=9EzRmuLbK6oTI2zLx%2fFeoFc4nlfwlSVJh7c0rQ%2fMaUo%3d',
  headers: { 
    'Content-Type': 'application/json'
  },
  data : data
};



const start = () =>{
  axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
  
      
}

const stop = () =>{
  axios(configStop)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
}
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

      <div style={{display:'flex',margin:'30px'}}>
  <button className={styles.card} onClick={start}> Start </button>
  <button className={styles.card}  onClick={stop}> Stop </button>
</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
